package com.mmall.dao;

import com.mmall.pojo.PayInfo;
import com.mmall.pojo.PayInfoExample;

public interface PayInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    int deleteByExample(PayInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    int insert(PayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    int insertSelective(PayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    PayInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    int updateByPrimaryKeySelective(PayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    int updateByPrimaryKey(PayInfo record);
}