package com.mmall.pojo;

import java.util.Date;

public class Shipping {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_shipping.id
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_shipping.user_id
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_shipping.receiver_name
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    private String receiverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_shipping.receiver_phone
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    private String receiverPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_shipping.receiver_mobile
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    private String receiverMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_shipping.receiver_province
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    private String receiverProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_shipping.receiver_city
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    private String receiverCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_shipping.receiver_district
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    private String receiverDistrict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_shipping.receiver_address
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    private String receiverAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_shipping.receiver_zip
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    private String receiverZip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_shipping.create_time
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_shipping.update_time
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_shipping
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    public Shipping(Integer id, Integer userId, String receiverName, String receiverPhone, String receiverMobile, String receiverProvince, String receiverCity, String receiverDistrict, String receiverAddress, String receiverZip, Date createTime, Date updateTime) {
        this.id = id;
        this.userId = userId;
        this.receiverName = receiverName;
        this.receiverPhone = receiverPhone;
        this.receiverMobile = receiverMobile;
        this.receiverProvince = receiverProvince;
        this.receiverCity = receiverCity;
        this.receiverDistrict = receiverDistrict;
        this.receiverAddress = receiverAddress;
        this.receiverZip = receiverZip;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_shipping
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    public Shipping() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_shipping.id
     *
     * @return the value of mmall_shipping.id
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_shipping.id
     *
     * @param id the value for mmall_shipping.id
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_shipping.user_id
     *
     * @return the value of mmall_shipping.user_id
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_shipping.user_id
     *
     * @param userId the value for mmall_shipping.user_id
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_shipping.receiver_name
     *
     * @return the value of mmall_shipping.receiver_name
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_shipping.receiver_name
     *
     * @param receiverName the value for mmall_shipping.receiver_name
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_shipping.receiver_phone
     *
     * @return the value of mmall_shipping.receiver_phone
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    public String getReceiverPhone() {
        return receiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_shipping.receiver_phone
     *
     * @param receiverPhone the value for mmall_shipping.receiver_phone
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    public void setReceiverPhone(String receiverPhone) {
        this.receiverPhone = receiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_shipping.receiver_mobile
     *
     * @return the value of mmall_shipping.receiver_mobile
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    public String getReceiverMobile() {
        return receiverMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_shipping.receiver_mobile
     *
     * @param receiverMobile the value for mmall_shipping.receiver_mobile
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    public void setReceiverMobile(String receiverMobile) {
        this.receiverMobile = receiverMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_shipping.receiver_province
     *
     * @return the value of mmall_shipping.receiver_province
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    public String getReceiverProvince() {
        return receiverProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_shipping.receiver_province
     *
     * @param receiverProvince the value for mmall_shipping.receiver_province
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    public void setReceiverProvince(String receiverProvince) {
        this.receiverProvince = receiverProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_shipping.receiver_city
     *
     * @return the value of mmall_shipping.receiver_city
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    public String getReceiverCity() {
        return receiverCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_shipping.receiver_city
     *
     * @param receiverCity the value for mmall_shipping.receiver_city
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    public void setReceiverCity(String receiverCity) {
        this.receiverCity = receiverCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_shipping.receiver_district
     *
     * @return the value of mmall_shipping.receiver_district
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    public String getReceiverDistrict() {
        return receiverDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_shipping.receiver_district
     *
     * @param receiverDistrict the value for mmall_shipping.receiver_district
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    public void setReceiverDistrict(String receiverDistrict) {
        this.receiverDistrict = receiverDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_shipping.receiver_address
     *
     * @return the value of mmall_shipping.receiver_address
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    public String getReceiverAddress() {
        return receiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_shipping.receiver_address
     *
     * @param receiverAddress the value for mmall_shipping.receiver_address
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    public void setReceiverAddress(String receiverAddress) {
        this.receiverAddress = receiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_shipping.receiver_zip
     *
     * @return the value of mmall_shipping.receiver_zip
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    public String getReceiverZip() {
        return receiverZip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_shipping.receiver_zip
     *
     * @param receiverZip the value for mmall_shipping.receiver_zip
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    public void setReceiverZip(String receiverZip) {
        this.receiverZip = receiverZip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_shipping.create_time
     *
     * @return the value of mmall_shipping.create_time
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_shipping.create_time
     *
     * @param createTime the value for mmall_shipping.create_time
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_shipping.update_time
     *
     * @return the value of mmall_shipping.update_time
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_shipping.update_time
     *
     * @param updateTime the value for mmall_shipping.update_time
     *
     * @mbggenerated Fri Nov 23 16:17:54 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}